Use gmtool after configuration has been done
Genymobile/genymotion-gradle-plugin pull request #20
Opened 2017-02-02 21:25 UTC by sgaland

In order to be able to use the plugin with configuration in the local.properties and without putting gmtool in the path, move some codes to be sure gmtool has been configured before using it to retrieve its version.

It works on my side for my use case, please review this to be sure there is no side effect I missed.

2017-02-02 21:41 UTC, eyal-lezmy requested changes

2017-02-02 21:41 UTC, eyal-lezmy commented on plugin/build.gradle
> +version = '1.4'
please don't bump the version

2017-02-02 21:41 UTC, eyal-lezmy commented on plugin/src/main/groovy/com/genymotion/GenymotionPluginExtension.groovy
> +            project.genymotion.config.version = gmtool.getVersion()
This should be outside the if (line 250) as it is needed whatever the config is set or not.

2017-02-02 23:42 UTC, sgaland commented on plugin/build.gradle
> +version = '1.4'
oups.

2017-02-02 23:43 UTC, sgaland commented on plugin/src/main/groovy/com/genymotion/GenymotionPluginExtension.groovy
> +            project.genymotion.config.version = gmtool.getVersion()
alright

2017-02-03 08:11 UTC, eyal-lezmy commented
Thanks for the modification. We need to find a way to test this bug efficiently before merging. I'll try to look at it next week but feel free to propose if you have time.

2017-08-04 12:00 UTC, eyal-lezmy approved these changes
Let's merge this on an integration branch and add unit tests!

2017-08-04 12:01 UTC, merged